// Book DATA
export const books = [
  {
    id: 1,
    title: "SAMANTHA, THE GIRL SCIENTIST",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/cover-front.jpg?v=1606227192",
    rating: 4.5,
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/044-SAMATHA-THE-GIRL-SCIENTIST-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589895893",
    description: "Curious Samantha  enjoys asking questions and trying to find their answers. Download this great free children’s illustrated book and make science fun with Samantha.",
    para: "Samantha the Girl Scientist is a fun book with two simple experiments for the inquiring mind. It’s intended to stimulate the young reader’s interest in the Sciences It is written towards the interests of girls. It’s prequel, Samuel the Boy Scientist, is written towards the interests of boys."
  },
  {
    id: 2,
    title: "MY NEW MATH TRICK",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/02_0923e561-fecf-4910-bf3c-3f07439a9717.jpg?v=1613561295",
    rating: 5,
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/048-MY-NEW-MATH-TRICK-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589895496",
    description: "This book is intended for any youngster (or maybe adult) who wants to overcome the challenge of the basic Times 9 Table or wants to be able to multiply two-digit numbers by 11 in their head.",
    para: "Yes, it takes a little practice but there are a couple of tricks to make it easier. Now, in 5 seconds, without the use of a calculator, or pencil and paper, what does 11 times 98 equal? The trick, using simple addition, is in this book.",
  },
  {
    id: 3,
    title: "LEARNING ABOUT \"NO\"",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/Learning_About_No.pdf?5538787067396429544",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/02_c95717e5-f5ea-4a89-bdeb-8abb6d3b66c6.jpg?v=1613633265",
    rating: 5,
    description: "Little Sophia didn’t understand adults at all. Why didn’t they just say ‘No’ for an answer? Here’s a great bed time story that helps both little and big readers appreciate a simple ‘No’",
  },
  {
    id: 4,
    title: "HOMEWORK - YUCK!",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/009-HOMEWORK-YUCK-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589846892",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/002_e9c00ff0-3d32-4eb6-aac3-6367393b358e.jpg?v=1613124972",
    rating: 4.5,
    description: "Jamal made a case at the next open house and it mattered much. Download this free children’s book to read about how he chose to stand his ground and took courage to validate his actions.",
    para: "A little bit of honesty and a little bit of courage had gone a long way in boosting Jamal’s belief in himself.  Read more in this free children’s real aloud and be truly inspired.",
  },
  {
    id: 5,
    title: "UP AND DOWN AND ALL AROUND",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/046-UP-AND-DOWN-AND-ALL-AROUND-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589895490",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/01_e6895152-a55f-4a63-a949-bcdacac5465c.jpg?v=1613626282",
    rating: 5,
    description: "Freddie went to town and there was plenty to see. All he had to do was look up and look down and look all around. As easy as it may seem, Freddie met with a few highs and lows on his day out.",
    para: "Read more in this free children’s good moral book available for download."
  },
  {
    id: 6,
    title: "SAMUEL, THE BOY SCIENTIST",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/045-SAMUEL-THE-BOY-SCIENTIST-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589895893",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/02_fd2b5841-e4aa-40ab-a991-bec26ba4d90e.jpg?v=1613546889",
    rating: 5,
    description: "Read this great free illustrated children’s book for a fun chemistry lesson with Samuel. He makes it look colorful, exciting and easy and that’s exactly how science should be.",
    para: "Samuel the Boy Scientist is a fun book with two simple experiments for the inquiring mind. It’s intended to stimulate the young reader’s interest in the Sciences and written towards the interests of boys. It’s sequel, Samantha the Girl Scientist, is written towards the interests of girls.",
  },
  {
    id: 7,
    title: "DO YOU WONDER HOW THE LADYBUG GOT ITS NAME?",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/036-DO-YOU-WONDER-HOW-THE-LADYBUG-GOT-ITS-NAME-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589893043",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/01_c1a12f92-69ab-44ef-9175-66a4e3351a09.jpg?v=1613469074",
    rating: 4,
    description: "Those little beauties have inspired so many stories. But where oh where did they get their name from? Why are they called the ladybugs?",
    para: "A tale that tells us emphatically that everything on earth has a purpose to serve. A free children’s book read aloud that is an absolute treat.",
  },
  {
    id: 8,
    title: "DO YOU WONDER HOW SNAKES SLITHER?",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/033-DO-YOU-_WONDER-HOW-SNAKES-SLITHER-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589893042",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/Do-You-Wonder-How-Snake-Slither_ef83c503-9580-4870-b06a-09a2d7649e0c.jpg?v=1613466359",
    rating: 4.5,
    description: "There is a chatty snake in the garden and its on a monologue. Would you stop and listen or would you rather run? But before you decide, know this for sure..that this snake is no ordinary, he is quite the charmer.",
    para: "Download our free children’s book to read more about Slither the Snake.",
  },
  {
    id: 9,
    title: "THE WAY OF THE WOODS",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/028-THE-WAY-OF-THE-WOODS-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589890645",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/01_c467c1ed-49da-449b-84c5-eb6d2baa90ce.jpg?v=1613458208",
    rating: 4.5,
    description: " Shh!  Did you hear that? The jungle’s saying a story and you cannot afford to miss it. A colorful narrative set in the woods..camouflaged as a free children’s dog story.",
    para: "Happy Reading!"
  },
  {
    id: 10,
    title: "PIRATES COVE",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/027-PIRATES-COVE-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589890644",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/01_d942a19b-5799-4eb2-9adc-80e614562e5f.jpg?v=1613456878",
    rating: 5,
    description: "Sandy chances upon an old treasure map and as the events roll out one after another, he becomes richer both by pennies and by thoughts.",
    para: "Here’s a treasure hunt to embark upon  in this free children’s storybook. Sail Away Captain! The seven seas are yours..",
  },
  {
    id: 11,
    title: "DO YOU WONDER ABOUT RAIN, SNOW, SLEET AND HAIL?",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/021-DO-YOU-WONDER-ABOUT-RAIN-SNOW-SLEET-AND-HAIL-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589890643",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/002_bf7c72c0-1203-4ce5-a714-ea9f1681b142.jpg?v=1613387410",
    rating: 5,
    description: " “What’s to wonder about water?”, you might ask.",
    para: "Professor Ture will tell you why.  Filled with compelling illustrations, this free children’s book takes a dive  into a whirlpool of knowledge about the ubiquitous water that we often take for granted.",
  },
  {
    id: 12,
    title: "THE HIKE",
    download: "https://cdn.shopify.com/s/files/1/2081/8163/files/026-THE-HIKE-Free-Childrens-Book-By-Monkey-Pen.pdf?v=1589890640",
    url: "https://cdn.shopify.com/s/files/1/2081/8163/files/01_36129a87-831c-4ff4-801e-36613ca1ef53.jpg?v=1613455461",
    rating: 4.5,
    description: "Mandy and grandpa went on a hike . But it was more than that. Together they explored the woods, learnt to be at peace with nature and talked their hearts out about things that mattered. It was a special bond between them and you’ve got to read this great free illustrated children’s book to experience it.",
    para: "Happy Exploring!!",
  },
];